# Site settings
title: justnewbee's github pages
email: justnewbee@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  start using github as my blogging tool
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://justnewbee.github.io" # the base hostname & protocol for your site
twitter_username: justnewbee
github_username: justnewbee

# Build settings
# markdown: kramdown
highlighter: pygments
markdown: redcarpet
